spring.application.name=barbersync-api

spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.password=@BarberSync123
spring.datasource.username=postgres.qthnwcemnlzzqickslyg

api.security.secret=RegisterBarberSync456

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
