spring.application.name=barbersync-api

spring.datasource.url=jdbc:postgresql://db.qthnwcemnlzzqickslyg.supabase.co:5432/postgres
spring.datasource.password=@BarberSync123
spring.datasource.username=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
